name: smart_bus_tracker
description: A real-time bus tracking and occupancy system.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Core Backend & Maps
  supabase_flutter: ^2.6.0
  google_maps_flutter: ^2.9.0
  geolocator: ^12.0.0
  image_picker: ^1.0.7
 # --- CORE UTILS ---
  http: ^1.1.0
  uuid: ^4.0.0
  
  # --- GOOGLE MAPS & PLACES (Use these EXACT versions) ---
  # The maintained fork that supports http ^1.1.0
  flutter_google_places_hoc081098: ^2.0.0 
  
  # The compatible webservice package
  google_maps_webservice_ex: ^0.0.1+3
  
  # Headers utility (required by maps)
  google_api_headers: ^4.0.3

  # --- COMPATIBILITY FIX ---
  # Do NOT use version 9.0.0 yet; it breaks google_api_headers
  package_info_plus: ^8.3.0
  
  # Utilities
  intl: ^0.20.0      # For date formatting
  permission_handler: ^11.0.0 # Better permission requests
  provider: ^6.1.5+1
  flutter_polyline_points: ^3.1.0
  shared_preferences: ^2.2.0 # To save the selected language
  flutter_gen: ^5.12.0
  google_mlkit_translation: ^0.10.0
  flutter_localizations:
    sdk: flutter
  flutter_dotenv: ^6.0.0
  google_mlkit_language_id: ^0.13.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
  generate: true
  assets:                 # <--- ADD THIS SECTION
    - .env